# Generated by Django 3.2.14 on 2022-07-04 20:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('active_chat', models.BooleanField()),
                ('city', models.CharField(max_length=125)),
                ('zone', models.CharField(max_length=125)),
                ('confirmed', models.BooleanField()),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('long', models.DecimalField(decimal_places=2, max_digits=5)),
                ('show_phone', models.BooleanField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('special', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_ad', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
