# Generated by Django 3.2.14 on 2022-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wantads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wantad",
            name="data",
            field=models.JSONField(),
        ),
    ]
