# Generated by Django 3.2.14 on 2022-07-04 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wantads', '0002_alter_wantad_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wantad',
            options={'ordering': ('special', 'created')},
        ),
        migrations.AlterField(
            model_name='wantad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_ad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WantAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('want', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wantads.wantad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
