# Generated by Django 3.2.14 on 2022-07-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wantads', '0004_message_saved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WantAdImage',
            new_name='Image',
        ),
    ]
