# Generated by Django 3.2.14 on 2022-07-05 20:45

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wantads", "0006_auto_20220706_0015"),
    ]

    operations = [
        migrations.CreateModel(
            name="Viewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ("updated", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wantads_viewed",
                        related_query_name="wantads_viewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "want",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wantads_viewed",
                        related_query_name="wantads_viewed",
                        to="wantads.wantad",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
